namespace SiteBuilder.Host.Bridge;

// 出力エンジンの選択（計画書 §2.7）/ output engine selection (plan §2.7).
//   Js     : 従来どおり renderer(JS) が生成した files をそのまま書き出す（既定・挙動不変）。
//            Write the files generated by the renderer (JS) as-is (default; unchanged behaviour).
//   Shadow : JS の出力を書き出しつつ、C# エンジンの出力と毎回比較して不一致をログに残す。
//            Write the JS output, but also compare against the C# engine each time and log mismatches.
//   CSharp : project.json から C# エンジンで再生成した files を書き出す。
//            Regenerate and write files from project.json using the C# engine.
public enum EngineMode
{
    Js,
    Shadow,
    CSharp,
}

public static class EngineModeParser
{
    // --engine=js|shadow|csharp または 環境変数 SITEBUILDER_ENGINE。既定は Js（挙動不変）。
    // --engine=js|shadow|csharp or the SITEBUILDER_ENGINE env var. Defaults to Js (no behaviour change).
    public static EngineMode Resolve(string[] args)
    {
        string? value = null;
        foreach (var a in args)
            if (a.StartsWith("--engine=", StringComparison.OrdinalIgnoreCase))
                value = a["--engine=".Length..];
        value ??= Environment.GetEnvironmentVariable("SITEBUILDER_ENGINE");

        return (value?.Trim().ToLowerInvariant()) switch
        {
            "csharp" or "c#" => EngineMode.CSharp,
            "shadow" => EngineMode.Shadow,
            _ => EngineMode.Js,
        };
    }
}
